In [2]:
import numpy as np

In [2]:
#lesson 7 Numpy with udacity 
# video 4 ############################################## Creating and Saving NumPy ndarrays
# first way to creat array(matrix)
#one dimention array  == 1D array
x1 = np.array([1,2,3,4,5])
print(x1)
print(type(x1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x1.dtype

dtype('int32')

In [5]:
x1.shape

(5,)

In [8]:
x1.size

5

In [6]:
# creat 2d array >> two dimention array
x2 = np.array([[1,2,3],[5,6,7],[8,9,4],[11,12,13]])
print(x2)


[[ 1  2  3]
 [ 5  6  7]
 [ 8  9  4]
 [11 12 13]]


In [7]:
x2.shape

(4, 3)

In [9]:
x2.size

12

In [13]:
#int and float data type   convert int >> float to upcasting
x3 = np.array([1,5.6,10.4])
print(x3,x3.dtype)

[ 1.   5.6 10.4] float64


In [17]:
#mix array data type
x4 = np.array([1,5,"world"])
print(x4)
print('shape : ' , x4.shape)
print('type : ' , type(x4))
print('dtype : ' , x4.dtype)

['1' '5' 'world']
shape :  (3,)
type :  <class 'numpy.ndarray'>
dtype :  <U11


In [18]:
# save array 
x5 = np.array([1,2,5,4,7,8,10])
np.save('my array',x5)

In [19]:
#load array 
x6 = np.load('my array.npy')
print(x6)

[ 1  2  5  4  7  8 10]


In [21]:
#quiz
# create numpy array of letters a-j
letter_array = np.array(['a','b','c','d','e','f','g','h','i','j'])
print("Letter Array: ", letter_array)

# get dtype of array
print('the type',type(letter_array))
print('the dtype',letter_array.dtype)## string

# get shape of array
print('the shape',letter_array.shape)

# get size of array
print('the size',letter_array.size)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
the type <class 'numpy.ndarray'>
the dtype <U1
the shape (10,)
the size 10


In [22]:
#conver list to array
x7 = [20,64,12,452]
x8 = np.array(x7)
print(x8)

[ 20  64  12 452]


In [23]:
# video7 ##############################################
#using built in functions to create ndarray 
# create zeros array with shape i define it 
y1 = np.zeros((3,4))
print(y1)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
print('dtype is : ',y1.dtype)

dtype is :  float64


In [25]:
#changing type
y1 = np.zeros((3,4),dtype=int)
print(y1,y1.dtype)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int32


In [27]:
#create ones arrat\y
y2 = np.ones((4,5))
print(y2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
#create full array with fill number i define it 
y3 = np.full((4,6),8)
print(y3)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [29]:
# create identity matrix == square matrix
y4 = np.eye(5)
print(y4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
# create diagonal matrix
y5 = np.diag([10,50,40,160,70])
print(y5)

[[ 10   0   0   0   0]
 [  0  50   0   0   0]
 [  0   0  40   0   0]
 [  0   0   0 160   0]
 [  0   0   0   0  70]]


In [31]:
# create matrix with numbers in range with arange(start,stop,step) function
#with one argument
y6 = np.arange(10)
print(y6)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
y6 = np.arange(4,10)
print(y6)

[4 5 6 7 8 9]


In [33]:
y6 = np.arange(4,10,2)
print(y6)

[4 6 8]


In [40]:
#create arange of distributed number linspace(start,stop,n)
y7 = np.linspace(0,25,20)
print(y7)

[ 0.          1.31578947  2.63157895  3.94736842  5.26315789  6.57894737
  7.89473684  9.21052632 10.52631579 11.84210526 13.15789474 14.47368421
 15.78947368 17.10526316 18.42105263 19.73684211 21.05263158 22.36842105
 23.68421053 25.        ]


In [43]:
#we can reshape any array for any n*m matrix
y7 = np.reshape(y7,(4,5)).reshape(10,2)
print(y7)

[[ 0.          1.31578947]
 [ 2.63157895  3.94736842]
 [ 5.26315789  6.57894737]
 [ 7.89473684  9.21052632]
 [10.52631579 11.84210526]
 [13.15789474 14.47368421]
 [15.78947368 17.10526316]
 [18.42105263 19.73684211]
 [21.05263158 22.36842105]
 [23.68421053 25.        ]]


In [42]:
# y7 = np.reshape(y7,(10,2))
# print(y7)

[[ 0.          1.31578947]
 [ 2.63157895  3.94736842]
 [ 5.26315789  6.57894737]
 [ 7.89473684  9.21052632]
 [10.52631579 11.84210526]
 [13.15789474 14.47368421]
 [15.78947368 17.10526316]
 [18.42105263 19.73684211]
 [21.05263158 22.36842105]
 [23.68421053 25.        ]]


In [44]:
# random function to create random array its useful for machine learning to intialize neural networks
y8 = np.random.random((3,3))
print(y8)

[[0.54564453 0.90664512 0.4664343 ]
 [0.02800076 0.31697562 0.15292721]
 [0.76051369 0.62128127 0.57521548]]


In [50]:
# create random int np.random.random(lower,upper,(3,3)==shape)
y9 = np.random.randint(4,15,(5,5))
print(y9)

[[11 10  4  9 13]
 [ 6 11 10 10  9]
 [12 10 10 11 12]
 [ 9 11  5 13  5]
 [ 4 14 14  5  7]]


In [54]:
y10 = np.random.normal(0,0.1,size=(1000,1000))
print(y10)

[[-0.01105177 -0.0668551  -0.08656313 ...  0.03125777 -0.02838849
  -0.06771909]
 [-0.02792225 -0.05854278  0.04430142 ...  0.09108573  0.06994427
   0.08119593]
 [ 0.01242272 -0.0919275  -0.06512197 ...  0.27871942 -0.11931659
  -0.13128963]
 ...
 [-0.0598965  -0.11468067  0.13460958 ...  0.09915817  0.08468082
  -0.25959056]
 [ 0.02237189  0.10512158 -0.0893913  ... -0.03488999  0.1217876
  -0.01262713]
 [ 0.16037298 -0.18856382  0.04781941 ... -0.09928428  0.02995565
  -0.03609242]]


In [56]:
print('mean',y10.mean())
print('std',y10.std())
print('max',y10.max())
print('#positive',(y10>0).sum())
print('#negative',(y10<0).sum())


mean 0.00010750943195313815
std 0.09994791749744063
max 0.4735024700441054
#positive 500867
#negative 499133


In [57]:
# video9 ##############################################
#Accessing, Deleting, and Inserting Elements Into ndarrays
z1 = np.array([1,2,5,8,9,3])
print('1st element ' , z1[0])
print('2st element ' , z1[1])
print('3st element ' , z1[2])
print('5st element ' , z1[4])

1st element  1
2st element  2
3st element  5
5st element  9


In [59]:
#negative indices
print('last element ' , z1[-1])
print('befor last element ' , z1[-2])

last element  3
befor last element  9


In [60]:
#modify elements in array 
z1[1]=200
print(z1)

[  1 200   5   8   9   3]


In [61]:
#another example
z2 = np.arange(1,10).reshape(3,3)
print(z2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
print('element at (0,0) : ',z2[0,0])
print('element at (0,2) : ',z2[0,2])
print('element at (2,2) : ',z2[2,2])

element at (0,0) :  1
element at (0,2) :  3
element at (2,2) :  9


In [63]:
#modify element
z2[0,2] = 700
print(z2)

[[  1   2 700]
 [  4   5   6]
 [  7   8   9]]


In [65]:
#add and delet elements in array==matrix in numpy
#delete using delete function
#array with rank 1 
z3 = np.array([1,2,3,4,5])
z3 = np.delete(z3,[0,4])
print(z3)

[2 3 4]


In [73]:
#delete from array with rank 2 
z4 = np.arange(1,10).reshape(3,3)
print(z4)
print("===============")
z5 = np.delete(z4,0,axis=0 )#raw
print(z5)
print("===============")
z6 = np.delete(z4,[0,2],axis=1)#colomn     [0,2] mean that delete colomn with index 0 and delete colomn with index 2 
print(z6)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[2]
 [5]
 [8]]


In [76]:
#add element to array using append(array,element want to add) function in array with rank 1
z7 = np.array([1,2,3,4,5])
print(z7)
z7 = np.append(z7,8)
print(z7)
z7 = np.append(z7,[7,9])
print(z7)

[1 2 3 4 5]
[1 2 3 4 5 8]
[1 2 3 4 5 8 7 9]


In [85]:
#add element to array using append(array,element want to add) function in array with rank 2

z8 = np.arange(1,10).reshape(3,3)
print(z8)
print("========")
#add row 
z8 = np.append(z8,[[10,20,30]],axis=0)
print(z8)
#add colomn
z8 = np.append(z8,[[10],[20],[30],[40]],axis=1)
print(z8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
[[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]
 [10 20 30 40]]


In [5]:
#insert numbers in array with rank 1 
z9 = np.array([10,20,30,40,50,60])
print(z9)
z9 = np.insert(z9,2,[1000,7000])
print(z9)

[10 20 30 40 50 60]
[  10   20 1000 7000   30   40   50   60]


In [7]:
# insert numbers in array with rank 2  >>> np.insert(array,index,elements want to insert)
z10 = np.array([[1,2,3,4],[5,6,7,8]])
print(z10)
#insert row 
z10 = np.insert(z10,1,[9,10,11,12],axis=0)#row
print(z10)
#insert colomn
z10 = np.insert(z10,1,[1000,2000,3000],axis=1)#colomn
print(z10)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]
[[   1 1000    2    3    4]
 [   9 2000   10   11   12]
 [   5 3000    6    7    8]]


In [14]:
# stack == compine arrays 
#vstack and hstack 
z11= np.array([2,5])
z12= np.array([[4,6],[10,20]])

z13 = np.vstack((z11,z12))
print(z13)
print("==============================")
z14 = np.hstack((z12,z11.reshape(2,1)))
print(z14)

[[ 2  5]
 [ 4  6]
 [10 20]]
[[ 4  6  2]
 [10 20  5]]


In [15]:
#video 10 ##########################################
#Slicing ndarrays
# three way for slicing
#1- >> ndarray[start index:end index]
#2- >> ndarray[start:]
#3- >> ndarray[:end]
# example with rank 2 array
# index start from 0 
a1 = np.arange(1,21).reshape(4,5)
print(a1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
a2 = a1[1:4,2:5] ## [1:4 rows,2:5 colomns]
print(a2)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [18]:
a2 = a1[1:,2:] ## [1:4 rows,2:5 colomns]
print(a2)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [19]:
a2 = a1[:3,2:] ## [1:4 rows,2:5 colomns]
print(a2)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [21]:
a2 = a1[:,2] ## [: all rows,in colomn 2]
print(a2)

[ 3  8 13 18]


In [23]:
a2 = a1[:,2:3] ## [1:4 rows,2:5 colomns]
print(a2)

[[ 3]
 [ 8]
 [13]
 [18]]


In [30]:
# if a4 depend on a3 and i change a4 a3 will changed 
a3 = np.arange(1,21).reshape(4,5)
print(a3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
a4 = a3[1:,2:]
print(a4)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [32]:
a4[2,2] = 555
print(a4)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [33]:
# a3 changed because a4 changed 
print(a3)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [34]:
#if i want a3 be constant not changed we use copy function in numpy 
# we tacke the ame example 
a5 = np.arange(1,21).reshape(4,5)
print(a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [35]:
a6 = np.copy(a5[1:,2:]) # a5[1:,2:].copy()
print(a6)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [36]:
a6[2,2] = 555
print(a6)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [37]:
#not changed
print(a5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [39]:
# extract diagonal fronm array k = 0 by default 
a7 = np.diag(a5)
print(a7)

[ 1  7 13 19]


In [40]:
a8 = np.diag(a5,k=1) # start from second colomn
print(a8)

[ 2  8 14 20]


In [41]:
# unique function == not repeated 
a9 = np.array([[1,2,3,4],[1,2,5,7],[9,8,7,5]])
print(a9)
a10=np.unique(a9)
print(a10)

[[1 2 3 4]
 [1 2 5 7]
 [9 8 7 5]]
[1 2 3 4 5 7 8 9]


In [42]:
# video 11 
#Boolean Indexing, Set Operations, and Sorting

d1 = np.arange(25).reshape(5,5)
print(d1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [45]:
#use boolean indexing to select element greater than 10
print(d1[d1>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [46]:
print(d1[d1<=7])

[0 1 2 3 4 5 6 7]


In [50]:
print(d1[(d1>10) & (d1<17)])

[11 12 13 14 15 16]


In [51]:
d1[(d1>10) & (d1<17)] = -1 
print(d1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [58]:
# some operation useful for comparing arrays 
# intersection,difference,union
d2 = np.array([1,2,3,4,5])
d3 = np.array([6,7,2,8,4])
print(np.intersect1d(d2,d3))
print(np.setdiff1d(d2,d3))
print(np.union1d(d2,d3))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [60]:
# sort == order
d4 = np.random.randint(1,11,size=(10,))
print(d4)

[4 8 6 7 4 3 1 6 1 1]


In [61]:
print(np.sort(d4))# have the repeated numbers
print(d4)#still not sorted

[1 1 1 3 4 4 6 6 7 8]
[4 8 6 7 4 3 1 6 1 1]


In [62]:
print(np.sort(np.unique(d4))) # sort the unique array

[1 3 4 6 7 8]


In [63]:
# sort 2 rank array
d5 = np.random.randint(1,11,size=(5,5))
print(d5)

[[ 1  2  1  6  2]
 [ 6  7  3 10  1]
 [ 1  9  4  3  4]
 [ 1 10  7  7  1]
 [ 5  3  1  1  8]]


In [64]:
#sort from row
print(np.sort(d5,axis=0))

[[ 1  2  1  1  1]
 [ 1  3  1  3  1]
 [ 1  7  3  6  2]
 [ 5  9  4  7  4]
 [ 6 10  7 10  8]]


In [65]:
#sort from row
print(np.sort(d5,axis=1))

[[ 1  1  2  2  6]
 [ 1  3  6  7 10]
 [ 1  3  4  4  9]
 [ 1  1  7  7 10]
 [ 1  1  3  5  8]]


In [70]:
# video 12 quize 
#Manipulating ndarrays
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.random.randint(1,26,size=(5,5))
print(X)
print("=======")
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X%2 != 0]
print(Y)

[[12  3 24 20  6]
 [25 24 13  6 19]
 [15 24 14 15 10]
 [ 7  1  4 15 12]
 [ 5 25 18 15  9]]
[ 3 25 13 19 15 15  7  1 15  5 25 15  9]


In [71]:
#video 13 
#Arithmetic Operations and Broadcasting
f1 = np.array([1,2,3,4,5])
f2 = np.array([6,7,8,9,10])
print(f1)
print(f2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [72]:
#make operation in arrays using sympols or functions
print(f1 + f2)
print(np.add(f1,f2))

[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [73]:
print(f1 * f2)
print(np.multiply(f1,f2))

[ 6 14 24 36 50]
[ 6 14 24 36 50]


In [74]:
print(f1 - f2)
print(np.subtract(f1,f2))

[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]


In [78]:
print(f1 / f2)
print(np.divide(f1,f2))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [83]:
f3 = np.array([1,2,3,4]).reshape(2,2)
print(f3)
f4 = np.array([5,6,7,8]).reshape(2,2)
print(f4)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [84]:
print(f3+f4)
print(f3-f4)
print(f3*f4)
print(f3/f4)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [86]:
#get square root and exponention and power 2

print(np.sqrt(f3))
print(np.exp(f4))
print(np.power(f3,2))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 148.4131591   403.42879349]
 [1096.63315843 2980.95798704]]
[[ 1  4]
 [ 9 16]]


In [91]:
#statistic function
# mean
print("the averages ",f3.mean(),"----",f4.mean())

print("the averages of rows  ",f3.mean(axis=1))
print("the averages of colomns  ",f3.mean(axis=0))


the averages  2.5 ---- 6.5
the averages of rows   [1.5 3.5]
the averages of colomns   [2. 3.]


In [92]:
#sum
print("the sum ",f3.sum(),"----",f4.sum())

print("the sum of rows  ",f3.sum(axis=1))
print("the sum of colomns  ",f3.sum(axis=0))

the sum  10 ---- 26
the sum of rows   [3 7]
the sum of colomns   [4 6]


In [93]:
# standard devision

print("the std ",f3.std(),"----",f4.std())

print("the std of rows  ",f3.std(axis=1))
print("the std of colomns  ",f3.std(axis=0))

the std  1.118033988749895 ---- 1.118033988749895
the std of rows   [0.5 0.5]
the std of colomns   [1. 1.]


In [95]:
#median
print("the median ",np.median(f3),"----",np.median(f4))



the median  2.5 ---- 6.5


In [96]:
#min max 
print("the min max ",f3.max(),"----",f4.min())


the min max  4 ---- 5


In [97]:
print(3+f3)

[[4 5]
 [6 7]]


In [98]:
print(f3-3)
print(3*f3)
print(f3/3)

[[-2 -1]
 [ 0  1]]
[[ 3  6]
 [ 9 12]]
[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [4]:
#video 14 last quize in numpy
#boadcasting
# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

# Do not change the name of this array. 
# Please don't print anything from your code! The TEST RUN button below will print your array. 
X =np.zeros(4)+np.array([1,2,3,4])
print(X)

[1. 2. 3. 4.]
